import type { FactLedger, Product, RunReport } from '../types.ts';
import { buildFactLedger } from '../ledger/fact-ledger.ts';
import { stripHtml } from '../brand/metrics.ts';

/**
 * The side-by-side a non-technical person reads (spec.md §6). "Before" is not a
 * strawman: it is the literal contents of the source catalog, which ships with
 * `body_html: ""` and `seo: {}` for every product.
 */

function factLine(ledger: FactLedger, factId: string): string | null {
  const entry = ledger.entries.find((e) => e.id === factId);
  if (!entry) return null;
  return `\`${entry.source}\` → ${entry.label}: **${entry.value}**`;
}

export function renderBeforeAfter(
  report: RunReport,
  products: Product[],
  handles: readonly string[],
): string {
  const byHandle = new Map(products.map((p) => [p.handle, p]));
  const resultByHandle = new Map(report.products.map((r) => [r.handle, r]));
  const language = report.locale === 'en' ? 'English' : 'Spanish';

  const lines: string[] = [
    `# Before / after — ${handles.length} products (${language})`,
    '',
    `Generated by \`${report.generatorId}\` · style guide \`${report.styleGuideVersion}\` · run date ${report.anchorDate}`,
    '',
    'The "before" column is not a strawman. It is what the catalog actually contains:',
    '`body_html` and `seo` are empty strings on all 12 products in the source file.',
    '',
    'The **Facts used** list under each product is the point of the whole pipeline. Every',
    'sentence above it traces to one of those lines, and anything that could not be traced',
    'would have stopped the product from being publishable at all.',
    '',
    '---',
    '',
  ];

  for (const handle of handles) {
    const product = byHandle.get(handle);
    const result = resultByHandle.get(handle);
    if (!product || !result) continue;

    lines.push(`## ${product.title}`, '');
    lines.push(`\`${handle}\` · ${product.product_type} · ${product.variants.length} variants`, '');

    if (result.status !== 'publishable' || result.copy === null) {
      lines.push(
        '> **Quarantined.** No copy was published for this product.',
        '',
        ...result.violations.map((v) => `> - \`${v.ruleId}\` ${v.message} — “${v.evidence}”`),
        '',
      );
      continue;
    }

    const copy = result.copy;
    lines.push(
      '### Before',
      '',
      '| Field | Value |',
      '|---|---|',
      '| Description | *(empty)* |',
      '| Meta title | *(empty)* |',
      '| Meta description | *(empty)* |',
      '| Image alt text | *(empty)* |',
      '',
      '### After',
      '',
      '**Description**',
      '',
      ...stripHtml(copy.bodyHtml)
        .split('\n\n')
        .map((paragraph) => `> ${paragraph.trim()}`)
        .flatMap((line) => [line, '>']),
      '',
      '| Field | Value | Length |',
      '|---|---|---|',
      `| Meta title | ${copy.metaTitle} | ${copy.metaTitle.length} / 60 max |`,
      `| Meta description | ${copy.metaDescription} | ${copy.metaDescription.length} / 140–160 |`,
      `| Image alt text | ${copy.imageAlt} | ${copy.imageAlt.length} chars |`,
      '',
      '**Facts used**',
      '',
    );

    const ledger = buildFactLedger(product);
    const factLines = copy.usedFactIds
      .map((factId) => factLine(ledger, factId))
      .filter((line): line is string => line !== null);
    lines.push(...factLines.map((line) => `- ${line}`), '');
    lines.push('---', '');
  }

  return lines.join('\n');
}
